---
- http://animemap.net/api/table/hokkaidou.json
- http://animemap.net/api/table/aomori.json
- http://animemap.net/api/table/iwate.json
- http://animemap.net/api/table/miyagi.json
- http://animemap.net/api/table/akita.json
- http://animemap.net/api/table/yamagata.json
- http://animemap.net/api/table/fukushima.json
- http://animemap.net/api/table/ibaraki.json
- http://animemap.net/api/table/tochigi.json
- http://animemap.net/api/table/gunma.json
- http://animemap.net/api/table/saitama.json
- http://animemap.net/api/table/chiba.json
- http://animemap.net/api/table/tokyo.json
- http://animemap.net/api/table/kanagawa.json
- http://animemap.net/api/table/niigata.json
- http://animemap.net/api/table/toyama.json
- http://animemap.net/api/table/ishikawa.json
- http://animemap.net/api/table/fukui.json
- http://animemap.net/api/table/yamanashi.json
- http://animemap.net/api/table/nagano.json
- http://animemap.net/api/table/gifu.json
- http://animemap.net/api/table/shizuoka.json
- http://animemap.net/api/table/aichi.json
- http://animemap.net/api/table/mie.json
- http://animemap.net/api/table/shiga.json
- http://animemap.net/api/table/kyoto.json
- http://animemap.net/api/table/osaka.json
- http://animemap.net/api/table/hyogo.json
- http://animemap.net/api/table/nara.json
- http://animemap.net/api/table/wakayama.json
- http://animemap.net/api/table/tottori.json
- http://animemap.net/api/table/shimane.json
- http://animemap.net/api/table/okayama.json
- http://animemap.net/api/table/hiroshima.json
- http://animemap.net/api/table/yamaguchi.json
- http://animemap.net/api/table/tokushima.json
- http://animemap.net/api/table/kagawa.json
- http://animemap.net/api/table/ehime.json
- http://animemap.net/api/table/kochi.json
- http://animemap.net/api/table/fukuoka.json
- http://animemap.net/api/table/saga.json
- http://animemap.net/api/table/nagasaki.json
- http://animemap.net/api/table/kumamoto.json
- http://animemap.net/api/table/oita.json
- http://animemap.net/api/table/miyazaki.json
- http://animemap.net/api/table/kagoshima.json
- http://animemap.net/api/table/okinawa.json
